### ISSUE TITLE
"http://packagist.test/packages.json" does not contain valid JSON 

### ISSUE THREAD

**Issue by tumainimosha** [Webysther/composer-mirror-docker#1]
I have tried running local mirror of composer with the docker image using below command

```bash
$ docker run --name mirror --rm -v /Users/tumaini/workspace/composer-cache:/public -e MAINTAINER_REPO='packagist.test' webysther/packagist-mirror
```

After container finishes executing following is file structure of the cache folder

<img width="758" alt="Screenshot 2019-06-29 at 13 10 57" src="https://user-images.githubusercontent.com/7481490/60382702-d2313b80-9a6f-11e9-9624-bc5283004af2.png">

I have pointed the cache folder to local virtualhost `http://packagist.test`, and configured composer to point to local repo

```bash
composer config -g repos.packagist composer http://packagist.test 
```

However, when I run composer update I get error
```
"http://packagist.test/packages.json" does not contain valid JSON 
```

Seems the `packages.json` file is a shortcut to zipped file and webserver unable render this as json.

**Comment by webysther** [comment]
Please refer [here](https://github.com/Webysther/packagist-mirror/issues/4#issuecomment-407570417) to fix this issue.
