### ISSUE TITLE
No ports exposed

### ISSUE THREAD

**Issue by cwilby** [Webysther/composer-mirror-docker#2]
I've managed to run the docker container, how can I see the port the mirror is listening on?

**Comment by webysther** [comment]
There no nginx inside, only the build of repository, this is useful to keep data fresh:

My crontab as a sample:

`*    *  * * * root docker run --name mirror --rm --device-read-bps /dev/xvda:600kb --device-write-bps /dev/xvda:600kb -e SLEEP=1 -v /var/www/html:/public webysther/packagist-mirror`
